# Handling Missing Data
***

In [72]:
import pandas as pd

In [86]:
dataframe = pd.read_csv("Excel and CSV Files/Ankara Weather Data.csv", sep = None, engine = "python", parse_dates = ["Date"])
dataframe.set_index("Date", inplace = True)
dataframe

            ﻿Index  Windspeed   Event  Temperature
Date
2021-01-01       0        8.0  Cloudy         15.0
2021-02-01       1        8.0  Cloudy         15.0
2021-03-01       2        7.0  Cloudy          NaN
2021-04-01       3        7.0     NaN         16.0
2021-05-01       4        6.0  Cloudy         18.0
2021-06-01       5        6.0     NaN         19.0
2021-07-01       6        NaN   Sunny         20.0
2021-08-01       7        NaN   Sunny          NaN
2021-09-01       8        5.0   Sunny          NaN
2021-10-01       9        4.0   Sunny          NaN
2021-11-01      10        5.0   Sunny         30.0
2021-12-01      11        3.0   Sunny         25.0
2021-01-13      12        4.0  Cloudy         20.0
2021-01-14      13        5.0     NaN          NaN
2021-01-15      14        6.0  Cloudy         14.0
2021-01-16      15        7.0   Rainy          NaN
2021-01-17      16        8.0   Rainy         12.0
2021-01-18      17        8.0     NaN         12.0
2021-01-19      18       10.0   Rainy         10.0
2021-01-21      19       15.0   Windy         15.0

In [90]:
new_df = dataframe.fillna(0)
new_df

            ﻿Index  Windspeed   Event  Temperature
Date
2021-01-01       0        8.0  Cloudy         15.0
2021-02-01       1        8.0  Cloudy         15.0
2021-03-01       2        7.0  Cloudy          0.0
2021-04-01       3        7.0       0         16.0
2021-05-01       4        6.0  Cloudy         18.0
2021-06-01       5        6.0       0         19.0
2021-07-01       6        0.0   Sunny         20.0
2021-08-01       7        0.0   Sunny          0.0
2021-09-01       8        5.0   Sunny          0.0
2021-10-01       9        4.0   Sunny          0.0
2021-11-01      10        5.0   Sunny         30.0
2021-12-01      11        3.0   Sunny         25.0
2021-01-13      12        4.0  Cloudy         20.0
2021-01-14      13        5.0       0          0.0
2021-01-15      14        6.0  Cloudy         14.0
2021-01-16      15        7.0   Rainy          0.0
2021-01-17      16        8.0   Rainy         12.0
2021-01-18      17        8.0       0         12.0
2021-01-19      18       10.0   Rainy         10.0
2021-01-21      19       15.0   Windy         15.0

In [ ]:
new_df = df.fillna({
    "Temperature"   : 0,
    "Windspeed"     : 0,
    "Event"         : "No Event"
})